# Generated by Django 3.1.3 on 2022-02-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_pic', models.ImageField(upload_to='image/%Y/%m/%d')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'image_post',
                'managed': False,
            },
        ),
    ]
