# Generated by Django 4.0.1 on 2022-02-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('t_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('t_name', models.CharField(db_column='name', max_length=50)),
                ('t_type', models.TextField(db_column='type')),
                ('t_job', models.CharField(db_column='job', max_length=50)),
                ('t_age', models.IntegerField(db_column='age')),
            ],
            options={
                'db_table': 'rest_api_test_kakaofriends',
                'managed': False,
            },
        ),
    ]
